version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
        - MYSQL_USER=aiomysql
        - MYSQL_PASSWORD=mypass
        - MYSQL_DATABASE=test_pymysql
        - MYSQL_ROOT_PASSWORD=mypass
    ports:
        - 3306:3306
